name: Gradzix-Core
version: '${project.version}'
main: me.xxgradzix.gradzixcore.Gradzix_Core
api-version: 1.17
authors: [xxGradzix]

depend: [WorldGuard, WorldEdit]


commands:
  givezdrapka:
    description: Daje 1 zdrapke
    permission: zdrapka.givezdrapka

  zdrapka:
    description: Pokazuje nagrody ze zdrapki

  chatopcje:
    description: Pokazuje opcje chatu

  givefirework:
    description: Daje 1 magiczna fajerwerke
    permission: magicznafajerwerka.givefajerwerka

  ustawienia:
    description: otwiera okno ustawien automatycznej sprzedaży i auto wymiany

  wymianaustawienia:
    description: otwiera gui ustawien wymiany
    permission: ustawienia.wymianaustawieniaitems

  panel:
    description: otwiera panel dla admina
    permission: panel.panelPermission

  umiejetnosci:
    description: Otwiera okno umiejetnosci

  modyfikatoryumiejetnosci:
    description: ustawia modyfikatory umiejetnosci
    permission: umiejetnosci.modyfikatoryumiejetnosci

  ulepsz:
    permission: ulepsz.ulepszcommand
    description: ulepsza zbroje za odlamki

  ulepszconfig:
    description: ustawia konfiguracje ulepszen
    permission: ulepsz.ulepszconfig

  giveodlamek:
    description: daje odlamek
    permission: umiejetnosci.giveodlamek

  sprzedazustawienia:
    description: Ustawia cene do autosprzedazy
    permission: ustawienia.sprzedazustawienia

  setserverdamagemultiplier:
    description: ustawia serwerowe mnoznik damage
    usage: /setserverdamagemultiplier [multiplier]
    permission: serverConfig.damageConfig

  resetumiejetnosci:
    description: resetuje poziomy umiejetnosci wszystkich graczy
    permission: umiejetnosci.resetumiejetnosci
    usage: /resetumiejetnosci

  bazarwystaw:
    description: ma zastapic /bazar sell

  setpriorities:
    description: otwiera gui priorytetow
    permission: serverConfig.setpriorities
    usage: /setpriorities

  ais:
    description: Komenda dla itemshopu
    permission: serverConfig.ais

  odbierz:
    description: odbiera nagrode
    permission: rewardsystem.odbierz

  createGenerator:
    description: tworzy generator
    permission: generators.createGenerator
  setGenerator:
    description: umiejscawia generator
    permission: generators.setGenerator
  refreshGenerators:
    description: odswieza generator
    permission: generators.refreshGenerators

  showGenerators:
    description: otwiera gui generatorow generator
    permission: generators.showGenerators
  events:
    description: startuje event
    permission: events.startevent

  binds:
    description: plays binds
    permission: binds.binds


  jeziorkoconfig:
    description: nagrody z jeziorka
    permission: jeziorko.jeziorko

  jeziorko:
    description: pokazuje nagrody z jeziorka
    permission: jeziorko.nagrodyzjeziorka

  nagroda:
    description: otwiera gui nagrod
    permission: rewards.nagroda

  itemshop:
    description: otwiera item shop
    permission: itemshop.itemshop

  itemshopconfig:
    description: item shop config
    aliases:
      - isc
    permission: itemshop.itemshopconfig

  stankonta:
    description: item shop balance
    permission: itemshop.stankonta

  test:
    description: test

  wojna:
    description: wypowiada wojne

  wojny:
    description: menu wojen
