name: Gradzix-Core
version: '${project.version}'
main: me.xxgradzix.gradzixcore.Gradzix_Core
api-version: 1.17
authors: [xxGradzix]

depend: [WorldGuard,
         WorldEdit,
         FastAsyncWorldEdit,
         ProtocolLib, DecentHolograms]

softdepend: [PlaceholderAPI]

commands:
  givezdrapka:
    description: Daje 1 zdrapke
    permission: zdrapka.givezdrapka

  zdrapka:
    description: Pokazuje nagrody ze zdrapki

  chatopcje:
    description: Pokazuje opcje chatu

  givefirework:
    description: Daje 1 magiczna fajerwerke
    permission: magicznafajerwerka.givefajerwerka

  ustawienia:
    description: otwiera okno ustawien automatycznej sprzedaży i auto wymiany
    permission: gradzixcore.ustawienia

  wymianaustawienia:
    description: otwiera gui ustawien wymiany
    permission: ustawienia.wymianaustawieniaitems

  panel:
    description: otwiera panel dla admina
    permission: panel.panelPermission

  umiejetnosci:
    description: Otwiera okno umiejetnosci

  modyfikatoryumiejetnosci:
    description: ustawia modyfikatory umiejetnosci
    permission: umiejetnosci.modyfikatoryumiejetnosci

  ulepsz:
    permission: ulepsz.ulepszcommand
    description: ulepsza zbroje za odlamki

  ulepszconfig:
    description: ustawia konfiguracje ulepszen
    permission: ulepsz.ulepszconfig

  giveodlamek:
    description: daje odlamek
    permission: umiejetnosci.giveodlamek

  sprzedazustawienia:
    description: Ustawia cene do autosprzedazy
    permission: ustawienia.sprzedazustawienia

  setserverdamagemultiplier:
    description: ustawia serwerowe mnoznik damage
    usage: /setserverdamagemultiplier [multiplier]
    permission: serverConfig.damageConfig

  resetumiejetnosci:
    description: resetuje poziomy umiejetnosci wszystkich graczy
    permission: umiejetnosci.resetumiejetnosci
    usage: /resetumiejetnosci


  setpriorities:
    description: otwiera gui priorytetow
    permission: serverConfig.setpriorities
    usage: /setpriorities

#  ais:
#    description: Komenda dla itemshopu
#    permission: serverConfig.ais

  odbierz:
    description: odbiera nagrode
    permission: rewardsystem.odbierz

  createGenerator:
    description: tworzy generator
    permission: generators.createGenerator
  setGenerator:
    description: umiejscawia generator
    permission: generators.setGenerator
  refreshGenerators:
    description: odswieza generator
    permission: generators.refreshGenerators

  showGenerators:
    description: otwiera gui generatorow generator
    permission: generators.showGenerators
  events:
    description: startuje event
    permission: events.startevent

  binds:
    description: plays binds
    permission: binds.binds


  jeziorkoconfig:
    description: nagrody z jeziorka
    permission: jeziorko.jeziorko

  jeziorko:
    description: pokazuje nagrody z jeziorka
    permission: jeziorko.nagrodyzjeziorka

#  nagroda:
#    description: otwiera gui nagrod
#    permission: rewards.nagroda

  sklep:
    description: otwiera item shop

  itemshopconfig:
    description: item shop config
    aliases:
      - isc
    permission: itemshop.itemshopconfig

  stankonta:
    description: item shop balance
    permission: itemshop.stankonta

  configWojny:
    description: configWojny
    permission: clansextension.configwojny

  wypowiedzwojne:
    description: wypowiada wojne

  wojny:
    description: menu wojen
  incognito:
    description: incognito

  incognitoAdmin:
    permission: incognito.addIncognitoAdmin
    description: incognito

  givePerkBook:
    permission: perks.givePerkBook
    description: testuje perksy

  gamma:
    description: gamma

  perki:
    description: shows player perks levels
    aliases:
      - perks

  ulepszeniaklanu:
    description: menu ulepszen klanu

  setarmorattribute:
    description: sets armor atribute
    permission: armor.setarmoratribute
  ustawPerk:
    description: ustawia poziom perkow
    permission: perks.ustawPerk

  giveusuwacz:
    description: daje usuwacz
    permission: webremover.giveusuwacz

  bazar:
    description: otwiera bazar

  setAfkReward:
    description: ustawia nagrode za afk
    permission: afk.setAfkReward

  warp:
    description: otwiera gui warpow
    aliases: [warpy, warps]

  vip:
    description: otwiera vip menu

  svip:
    description: otwiera svip menu

  uni:
    description: otwiera age menu

  kosz:
    description: otwiera kosz

  osiagniecia:
    description: otwiera achievements

  codziennewyzwanie:
    description: codzienne wyzwanie
    aliases:
      - wyzwanie
      - wyzwania

  geteventitems:
    description: daje eventowe itemy
    permission: gradzixcore.giveEventItems

  setKillDropChance:
    description: ustawia szanse na dropienie itemow po zabiciu gracza
    permission: gradzixcore.setKillDropChance

  setDropChance:
    description: ustawia szanse na dropienie itemow po zabiciu gracza
    permission: gradzixcore.setKillDropChance


  #  test:
#    description: test

#  gracz:
#    description: pokazuje informacje o graczu
#
#  klan:
#    description: pokazuje informacje o klanie
#    aliases:
#      - k

  autosprzedaz:
    description:
    permission: gradzixcore.autosprzedaz

  gornik:
    description: pokazuje cene blokow w autosprzedazy
    permission: gradzixcore.gornik

  portfel:
    description: otwiera sklep

  dodajvpln:
    description: dodaje vpln
    permission: gradzixcore.dodajvpln

  upgradeshopeditor:
    description: tworzy sklepy ulepszec
    permission: gradzixcore.upgradeshop

  upgradeshop:
    description: otwiera sklep

  pomoc:
    description: okno pomocy

  kit:
    description: otwiera okno kitów

  createkit:
    description: tworzy kit
    permission: gradzixcore.createkit

  discord:
    aliases:
      - nagroda
    description: otwiera discord

  rangi:
    description: otwiera gui rang

  kiteditor:
    description: edycja kita
    permission: gradzixcore.kiteditor

  resetujDzienneWyzwania:
    description: resetuje progres
    permission: gradzixcore.resetujDzienneWyzwania